CREATE TABLE users(
    id BINARY(16) PRIMARY KEY,
    username VARCHAR(60) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE posts(
    id SERIAL AUTO INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    body TEXT NOT NULL,
    tags TEXT[10],
    users_id BINARY REFERENCES users(id),
    date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

DELIMITER $$

CREATE TRIGGER auto_id_on_insert
BEFORE INSERT ON users 
FOR EACH ROW
BEGIN
    IF NEW.id IS NULL THEN
        SET NEW.id = UUID_TO_BIN(UUID())
    END IF;
END $$

DELIMITER ;